### ISSUE TITLE
D+的封装方式是提供工具方法的方式来完成常用操作，D+的DNS查询操作对应用使用不透明

### ISSUE THREAD

**Issue by oldratlee** [onlytiancai/android-httpdns#1]
- 不透明，即走[`D+`](https://www.dnspod.cn/httpdns)工具方法的实现（应用实现）需要主动调用httpdns
- 因为不透明，其它使用域名的网络库 不能直接用上`D+`的域名解析能力，即需要一个一个修改或特殊配置网络库。

@onlytiancai 不知道在`Android`上你有没有办法，可以做对应用透明地用上`D+`的域名解析能力。

PS：

[`java-dns-cache-manipulator`](https://github.com/alibaba/java-dns-cache-manipulator/tree/master/library)这个库在`JRE`上实现了应用使用透明的`DNS`解析设置。

**Comment by onlytiancai** [comment]
https://github.com/SinaMSRE/HTTPDNSLib 新浪搞了一个，你看看

**Comment by oldratlee** [comment]
多谢！ 我看看先
